### ISSUE TITLE
Ошибка 23

### ISSUE THREAD

**Issue by zalcman** [vbatushev/InDex5#1]
Здравствуйте!
Запускаю ваш скрипт и выдает ошибку:

JavaScript Ошибка!

Номер ошибки: 23
Сообщение об ошибке: & does not have a value

Engine: main
Файл: C:\Program Files\Adobe\Adobe InDesign 2022\Scripts\Scripts Panel\index\InDex6.jsxbin
Строка: 28
Источник:     <meta name="optimizely-datafile" content="{&quot;groups&quot;: [], &quot;environmentKey&quot;: &quot;production&quot;, &quot;rollouts&quot;: [], &quot;typedAudiences&quot;: [], &quot;projectId&quot;: &quot;16737760170&quot;, &quot;variables&quot;: [], &quot;featureFlags&quot;: [], &quot;experiments&quot;: [{&quot;status&quot;: &quot;Running&quot;, &quot;audienceIds&quot;: [], &quot;variations&quot;: [{&quot;variables&quot;: [], &quot;id&quot;: 
и т. д.

Что я делаю не так?

**Comment by vbatushev** [comment]
Забираете скрипт неправильно, судя по всему. Вы либо его склонируйте (git clone https://github.com/vbatushev/InDex5.git), либо скачайте (кнопка Code, в открывающемся списке Download ZIP), либо скачайте jsxbin в RAW-виде: https://raw.githubusercontent.com/vbatushev/InDex5/master/InDex6.jsxbin

Кстати, ссылка на InDex6.jsxbin даже в README есть. Невнимательно читаем!

**Comment by zalcman** [comment]
Спасибо. Помогло, все работает.
